# -*- coding: utf-8 -*-
"""analyze-rdfs-data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DCPWNGOmRpH1tbLUa8z-kTcJy1H826At
"""

import pickle

import numpy as np

import matplotlib.pyplot as plt

from mygraphs import Hypercube
from myrdfs import rdfs, get_summary_stats

def read_file(fname):
    with open(fname, "rb") as f:
        return pickle.load(f)

def plot_file(fname):
    G, dist_stats = read_file(fname)
    summary_stats = get_summary_stats(dist_stats)
    G.plot_means_vars(summary_stats, fname=fname)

print("\n--- Plotting Hypercube Data ---")
plot_file("data/rdfs-hypercube-3d-20000-samples.pickle")
plot_file("data/rdfs-hypercube-4d-50000-samples.pickle")
plot_file("data/rdfs-hypercube-5d-100000-samples.pickle")