# -*- coding: utf-8 -*-
"""rdfs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xD5oKNGLymCAN83_ox3BrQ9RhpPCKQp_
"""

from matplotlib import collections as mc

import matplotlib.pyplot as plt

from graphs import Graph, Grid, TriangularLattice
from rdfs import rdfs, save_statistics

g = Grid(11, 11)

g.get_start_vertex()

g.get_adj_list((0, 0))

def plot_a_walk(n, m):
    G = Grid(n, m)
    start = G.get_start_vertex()
    visited_order = rdfs(G, start)

    fig, ax = plt.subplots()
    ax.add_collection(mc.LineCollection(visited_order))
    ax.autoscale()
    ax.margins(0.1)

plot_a_walk(5, 5)

# G = TriangularLattice(50)
# save_statistics(G, samples=10000)