# -*- coding: utf-8 -*-
"""run_hypercube_experiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13UtIWF-8MznODn8If3gDL4Mu4Lh2P8fo
"""

import os

if not os.path.exists('data'):
    os.makedirs('data')

# This script runs the rDFS simulation on Hypercube graphs and saves the results.

from mygraphs import Hypercube
from myrdfs import save_statistics

# --- Experiment on a 3D Hypercube (a cube) ---
print("--- Running on 3D Hypercube (8 vertices) ---")
# Starting with high sample count for smallest graph
cube = Hypercube(d=3)
save_statistics(cube, samples=100000)
print("Saved data for 3D hypercube.")


# --- Experiment on a 4D Hypercube (a tesseract) ---
print("\n--- Running on 4D Hypercube (16 vertices) ---")
tesseract = Hypercube(d=4)
save_statistics(tesseract, samples=50000)
print("Saved data for 4D hypercube.")


# --- Experiment on a 5D Hypercube ---
print("\n--- Running on 5D Hypercube (32 vertices) ---")
penteract = Hypercube(d=5)
save_statistics(penteract, samples=25000)
print("Saved data for 5D hypercube.")


# --- Experiment on a 6D Hypercube ---
print("\n--- Running on 6D Hypercube (64 vertices) ---")
hexeract = Hypercube(d=6)
save_statistics(hexeract, samples=10000)
print("Saved data for 6D hypercube.")


# --- Experiment on a 7D Hypercube ---
print("\n--- Running on 7D Hypercube (128 vertices) ---")
hepteract = Hypercube(d=7)
save_statistics(hepteract, samples=5000)
print("Saved data for 7D hypercube.")


# --- Experiment on an 8D Hypercube ---
print("\n--- Running on 8D Hypercube (256 vertices) ---")
octeract = Hypercube(d=8)
save_statistics(octeract, samples=2000)
print("Saved data for 8D hypercube.")


# --- Experiment on a 9D Hypercube ---
print("\n--- Running on 9D Hypercube (512 vertices) ---")
enneract = Hypercube(d=9)
save_statistics(enneract, samples=1000)
print("Saved data for 9D hypercube.")


# --- Experiment on a 10D Hypercube ---
print("\n--- Running on 10D Hypercube (1024 vertices) ---")
dekeract = Hypercube(d=10)
save_statistics(dekeract, samples=500)
print("Saved data for 10D hypercube.")

print("\nAll hypercube experiments complete!")

# -*- coding: utf-8 -*-
"""analyze-rdfs-data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DCPWNGOmRpH1tbLUa8z-kTcJy1H826At
"""

import pickle

import numpy as np

import matplotlib.pyplot as plt

from mygraphs import Hypercube
from myrdfs import rdfs, get_summary_stats

def read_file(fname):
    with open(fname, "rb") as f:
        return pickle.load(f)

def plot_file(fname):
    G, dist_stats = read_file(fname)
    summary_stats = get_summary_stats(dist_stats)
    G.plot_means_vars(summary_stats, fname=fname)

print("\n--- Plotting Hypercube Data ---")
plot_file("data/rdfs-hypercube-3d-100000-samples.pickle")
plot_file("data/rdfs-hypercube-4d-50000-samples.pickle")
plot_file("data/rdfs-hypercube-5d-25000-samples.pickle")
plot_file("data/rdfs-hypercube-6d-10000-samples.pickle")
plot_file("data/rdfs-hypercube-7d-5000-samples.pickle")
plot_file("data/rdfs-hypercube-8d-2000-samples.pickle")
plot_file("data/rdfs-hypercube-9d-1000-samples.pickle")
plot_file("data/rdfs-hypercube-10d-500-samples.pickle")